<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<!-- Google tag (gtag.js) -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-NQ5WV78GR8"></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());

			gtag('config', 'G-NQ5WV78GR8');
		</script>
		<meta charset="UTF-8">
		<title>Criatividade na prática para o ambiente de negócios</title>
		<meta name="description" content="A criatividade é cada vez mais importante, para empresas e profissionais. Saiba tudo o que você precisa saber para não ficar para trás.">
		<link rel="stylesheet" type="text/css" href="/css/blog.css">
		<link rel="stylesheet" type="text/css" href="/css/jssor.css">
		<link rel="icon" type="image/png" href="https://www.marcosmayer.com.br/mm.png">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700|Unica+One|Cormorant+SC|Oswald:400" rel="stylesheet">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="canonical" href="https://www.marcosmayer.com.br/artigo/criatividade-na-pratica-para-o-ambiente-de-negocios/" />
		<script type="text/javascript">
			(function(c,l,a,r,i,t,y){
				c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
				t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
				y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
			})(window, document, "clarity", "script", "k5xq23y7c6");
		</script>
	</head>
	<body class="blog">
		<!-- Google Tag Manager (noscript) -->
			<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TFSDBSM"
			height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
		<!-- End Google Tag Manager (noscript) -->
		<div class="topnav" id="myTopnav">
			<a href="#"></a>
			<a href="/marcos-mayer/">Conheça</a>
			<a href="/palestras/">Palestras</a>
			<a href="/treinamento/">Treinamento</a>
			<a href="/blog/">Blog</a>
			<a href="/videos/">Vídeos</a>
			<a href="/contato/">Contato</a>
			<a href="javascript:void(0);" class="icon" onclick="myFunction()"><i class="fa fa-bars"></i></a>
		</div>
		<div class="header">
			<div class="logo"><a href="/"><img src="/images/logo-marcos-mayer.png" alt="Marcos Mayer - Criatividade e Inovação"></a></div>
			<nav>
				<ul class="menu">
					<li><a href="/marcos-mayer/">Conheça</a></li>
					<li><a href="/palestras/">Palestras</a></li>
					<li><a href="/treinamento/">Treinamento</a></li>
					<li><a href="/blog/">Blog</a></li>
					<li><a href="/videos/">Vídeos</a></li>
					<li><a href="/contato/">Contato</a></li>
				</ul>
			</nav>
			<div class="social">
				<a href="https://www.youtube.com/@marcosmayer" title="YouTube" target="_blank"><img src="/images/social-icon-youtube.png" alt="YouTube Marcos Mayer"></a>
				<a href="https://www.linkedin.com/in/marcosmayer/" title="LinkedIn" target="_blank"><img src="/images/social-icon-linkedin.png" alt="LinkedIn Marcos Mayer Palestrante"></a>
			</div>
		</div>
		<div class="container">
			<div class="content-container">
				<div class="text-container">
					<div class="blog-post">
						<article>
							<div class="blog-post-titulo-read"><h1>Criatividade na prática para o ambiente de negócios</h1></div>
							<div class="blog-info">
								<div class="blog-post-data">12 de fevereiro de 2019</div>
								<div class="blog-post-autor">Marcos Mayer</div>
							</div>
							<div class="blog-post-imagem"><img src="/images/blog/sm-criatividade-na-pratica-para-o-ambiente-de-negocios.jpg"></div>
							<div class="blog-post-texto">
								<p>A criatividade é, provavelmente, a capacidade menos apreciada no ambiente profissional, se comparada ao seu potencial de impacto positivo nesse mesmo ambiente. Isso se deve, principalmente, à falta de compreensão do que é a criatividade, tanto quanto do que a criatividade não é, e de quais são os principais benefícios práticos que o pensamento criativo oferece. Existe uma série de mitos a respeito da criatividade, que lhe conferem uma aura de algo meio nebuloso, que as pessoas precisam ter, sem saber exatamente o motivo, mas que apenas algumas pessoas receberam, como um dom inato. Para piorar ainda mais a questão, a maior parte das pessoas entende que apenas uma pequena parcela de profissionais precisa de criatividade para exercer seu papel, apenas aqueles que têm uma carreira criativa.</p>
								<p>Isso tudo precisa mudar. E está mudando. O tema começa a ser levado mais a sério, e lideranças empresariais já valorizam a capacidade criativa de seus profissionais e das empresas. Em parte, isso se deve a uma pressuposição, no mínimo, exagerada: a de que os robôs e a inteligência artificial vão acabar com todos os empregos, restando apenas alguns poucos profissionais que têm, desenvolvidas, capacidades que os robôs nunca terão. E a criatividade é uma delas. Posso garantir que esta não é a principal razão (se é que é uma) pela qual você deveria procurar desenvolver sua capacidade criativa. Mas razões existem. E são muito contundentes. Vamos tratar dessas razões e apresentar quais são os mitos que atrapalham a compreensão da criatividade e quais são os principais benefícios que o pensamento criativo traz.</p>
								<h2>Os CEOS e a importância da criatividade</h2>
								<p>Em 2010, a <span class="bold">IBM</span> realizou o seu <span class="destaque">Global CEO Study</span>, uma pesquisa realizada com mais de <span class="bold">1.500 CEOs de 60 países e de 33 indústrias diferentes</span>. Esta pesquisa mostrou que, segundo esses CEOs, mais do que rigor, disciplina na gestão, integridade e até mesmo visão, navegar, com sucesso, por um mundo cada vez mais complexo exigirá criatividade. Ainda segundo esse estudo, menos da metade dos líderes empresariais acredita que suas companhias estejam adequadamente preparadas para lidar com um ambiente de negócios altamente volátil e cada vez mais complexo. Para encarar essas mudanças, é preciso infundir criatividade por toda a organização.</p>
								<p>De acordo com os CEOs entrevistados, líderes criativos possuem uma série de características extremamente importantes, que os destacam de seus pares não criativos. Líderes criativos:</p>
								<ul class="topics">
									<li>esperam fazer mais mudanças no modelo de negócios, a fim de realizar suas estratégias;</li>
									<li>dão boas vindas à inovação disruptiva, encorajando outros a abandonar táticas desatualizadas e a assumir riscos calculados;</li>
									<li>consideram novos meios para mudar drasticamente a empresa para melhor, preparando o terreno para a inovação que os ajuda no engajamento mais efetivo;</li>
									<li>sentem-se confortáveis com a ambiguidade e experimentam para criar novos modelos de negócios;</li>
									<li>avaliam a inovação como sendo muito mais importante, uma capacidade crucial;</li>
									<li>são corajosos e visionários o suficiente para tomar decisões que alterem o estado das coisas;</li>
									<li>inventarão novos modelos de negócios baseados em pressuposições completamente diferentes.</li>
								</ul>
								<p>Vale lembrar que essa pesquisa foi realizada quando o mundo estava saindo de sua última grande crise econômica, a de 2008, aquela que, no Brasil, seria apenas uma “marolinha”.</p>
								<p>“Saindo da pior crise econômica de nossas vidas profissionais—e deparando-se com um novo ‘normal’, que é claramente diferente—, <span class="destaque">é impressionante que os CEOS tenham identificado a criatividade como a competência de liderança número um da empresa de sucesso do futuro</span>”, disse <span class="bold">Frank Kern</span>, vice-presidente sênior da <span class="bold">IBM Global Business Services</span>. “Mas dê um passo para trás e pense a respeito, e isso será totalmente consistente com outra descoberta importante do estudo, a de que o maior desafio à frente das empresas, daqui em diante, será a complexidade cada vez mais acelerada e a velocidade de um mundo que está operando como um sistema massivo interconectado”.</p>
								<p>Desse estudo, realizado há nove anos, vamos destacar duas conclusões muito evidentes. A primeira delas é que se em 2010 a maior preocupação das lideranças empresariais era a velocidade das mudanças e a complexidade do nosso mundo, então, quase dez anos depois, essa questão não apenas continua valendo, mas é ainda mais decisiva no ambiente de trabalho. E a segunda é a clara razão da escolha da criatividade como o fator mais importante para lidar com tais mudanças. É que se a gente precisa se preparar para uma mudança, para um novo desafio, mas a gente não sabe exatamente que desafio será esse, não adianta focar na melhoria de uma capacidade específica, porque nem é possível saber se tal capacidade ainda terá qualquer utilidade quando a mudança chegar. Então, o melhor a fazer, é desenvolver a criatividade, que é capaz de nos ajudar a enfrentar qualquer desafio, qualquer que seja a mudança. (Os responsáveis pela educação em nosso país fariam muito bem em aprender essa lição. Mas isso é tema para outro artigo.)</p>
								<p>Nesse contexto, a principal característica de pessoas com a criatividade desenvolvida é que elas não apenas não temem mudanças, mas gostam delas. A mudança—o novo e desconhecido—é enxergada como um desafio a ser vencido, que serve como motivação para os criativos, como uma oportunidade, não como um problema. Existe um conceito fundamental na administração que ensina que, quando uma empresa ou um produto atingir seu auge, é hora de mudar, até ao ponto de, em alguns casos, adotar uma estratégia que vá matar seu produto de sucesso. Muitas empresas já foram extintas por não respeitarem esse conceito, sendo a <span class="bold">Kodak</span> e a <span class="bold">Blockbuster</span> dois dos cases mais conhecidos. Uma empresa criativa, com profissionais criativos, colocará esse tipo de mudança, tão disruptiva, em prática de forma natural, sem que isso se torne um problema.</p>
								<h2>Os profissionais em geral e a importância da criatividade</h2>
								<p>Em um outro estudo, realizado pela <span class="bold">Adobe</span>, em 2012, chamado <span class="destaque">State of Create Study</span>, o tema pesquisado foram as atitudes e crenças sobre a criatividade no trabalho, na escola e em casa. Foram entrevistados cinco mil adultos, de cinco países desenvolvidos: Alemanha, Estados Unidos, França, Japão e Reino Unido.</p>
								<p>Segundo esse estudo, <span class="destaque">oito em cada dez pessoas consideram que a criatividade é essencial para gerar crescimento econômico</span>, e dois terços entendem que ser criativo é muito importante para a sociedade como um todo. Entretanto, apenas uma em cada quatro pessoas afirma que está fazendo uso de seu potencial criativo na prática.</p>
								<p>O estudo mostra mais uma série de dados muito interessantes, como veremos a seguir, mas a própria forma como o estudo foi desenvolvido acabou gerando algumas aberrações nas respostas encontradas. Para dar base de sustentação a essa afirmação, eu gostaria de emprestar, de seu autor, a melhor definição de criatividade que eu já encontrei. Eu a considero tão precisa, que nunca tentei elaborar a minha própria definição, já que não considero que poderia fazer nada melhor do que <span class="bold">Sir Ken Robinson</span>, que afirmou que <span class="destaque">“criatividade é o processo de gerar ideias originais, que tenham valor”</span>. Quando uma definição é tão simples e, ao mesmo tempo, tão densa, é melhor não tentar melhorá-la. É a partir desta definição que eu faço a minha análise.</p>
								<p>Três em cada quatro entrevistados afirmam que existe uma crescente pressão para ser produtivo no trabalho, “ao invés” de ser criativo. Esse é o primeiro grande erro, que vem da compreensão equivocada do que é, e de qual é o papel da criatividade no trabalho. Nós até poderíamos afirmar que existe uma grande pressão pela produtividade “em vez” da criatividade, mas não “ao invés”. Quando dizemos “em vez”, estamos dizendo que algo está acontecendo no lugar de uma outra coisa que deveria estar acontecendo. Quando usamos “ao invés”, dizemos que o que está acontecendo é o oposto do que deveria estar acontecendo. Então a pergunta feita pressupõe que a produtividade e a criatividade são capacidades opostas: ou você é produtivo, ou criativo. E isso está muito longe da realidade. Antes, a criatividade é um fator que impulsiona a produtividade.</p>
								<p>Em outra questão da pesquisa que demonstra a falta de um claro entendimento de como a criatividade é aplicada na prática, os entrevistados deviam responder sobre qual porcentagem de seu tempo eles sentem que foram criativos. O estudo mostrou que as pessoas foram criativas durante 33% do tempo. Aqui fica claro que as pessoas percebem a criatividade como uma ferramenta, que pode ser utilizada, quando necessário ou quando possível, e depois guardada de volta na caixa de ferramentas, até ser utilizada novamente. Mas a criatividade não funciona como uma ferramenta. Ela pode ser entendida muito mais como uma lente, através da qual enxergamos e percebemos o mundo. Como tal, ela nunca precisaria ser guardada. Quem desenvolve sua criatividade, tem ela à sua disposição durante todo o tempo.</p>
								<p>Mas há esperança. Mais de 80% dos entrevistados consideraram cada uma das seguintes afirmações verdadeira:</p>
								<ul class="topics">
									<li>A imaginação é a base de onde a criatividade nasce;</li>
									<li>A criatividade começa com a expressão das minhas ideias;</li>
									<li>Todos temos o potencial e criar;</li>
									<li>A criatividade traz a minha imaginação à vida;</li>
									<li>A criatividade está em todo lugar nas nossas vidas, mas muitos não a enxergam;</li>
									<li>A habilidade de criar é ilimitada e não tem barreiras;</li>
									<li>Existe a necessidade de criar coisas novas e de trazer ideias inovadoras à vida.</li>
								</ul>
								<p>Apesar de algumas afirmações não serem muito acuradas, o retrato geral que elas nos apresentam é muito animador. As pessoas reconhecem a importância que a criatividade tem, quer seja no ambiente de trabalho, quer seja na sociedade como um todo.</p>
								<p>O último destaque que eu quero fazer a respeito desse estudo diz respeito ao principal motivo para que a maior parte das pessoas não tenha desenvolvido seu potencial criativo. Mais da metade dos entrevistados (59%, o que é muito pouco) atribui isso ao fato de que a criatividade está sendo sufocada pelo nosso sistema de educação. Vejam o que <span class="bold">Sir Ken Robinson</span> disse a esse respeito:</p>
								<p class="citacao">“Um dos mitos da criatividade é que muito poucas pessoas são realmente criativas. A verdade é que todos têm uma grande capacidade, mas nem todos a desenvolvem. Um dos problemas é que, em muitos casos, o nosso sistema de educação não possibilita aos estudantes desenvolverem seus poderes criativos naturais. Em vez disso, ele promove uniformidade e padronização. O resultado é que nos estamos drenando as possibilidades criativas das pessoas e, como esse estudo revela, produzindo uma força de trabalho que está condicionada a priorizar a conformidade sobre a criatividade.”</p>
								<h2>Os principais mitos que prejudicam a correta compreensão da criatividade</h2>
								<p>Ambos estudos apresentados neste artigo evidenciam a importância da criatividade e mostram que profissionais de todos os níveis reconhecem que ela precisa de mais espaço e reconhecimento, no ambiente de trabalho e na sociedade como um todo. Nesse cenário, é muito natural que façamos a seguinte pergunta: por que a criatividade não é valorizada como deveria ser?</p>
								<p>A resposta a essa pergunta, evidentemente, não é simples, mas passa pela criação e perpetuação de alguns mitos extremamente nocivos à compreensão da criatividade e dos benefícios que ela traz. Esses mitos fazem parte do imaginário popular a respeito da criatividade. Ninguém os questiona, nem para para pensar a respeito. Na verdade, esses mitos são a desculpa que a maior parte das pessoas usa para justificar sua falta de criatividade.</p>
								<p>Vamos conhecer alguns desses mitos e tentar derrubar cada um deles com bons argumentos.</p>
								<h3>Mito 1: Nem todas as pessoas são criativas e existem pessoas muito mais criativas do que outras.</h3>
								<p>É verdade que nem todas as pessoas são criativas, mas apenas porque não desenvolveram sua criatividade como poderiam, à altura do potencial criativo com que todos nascemos. Também é verdade que nem todas as pessoas sabem dirigir, mas todos têm a capacidade de aprender a dirigir. A ideia é a mesma. Da mesma forma, é verdade que existem pessoas muito mais criativas do que outras, mas apenas porque desenvolveram mais de seu potencial. Assim como existe o <span class="bold">Rubens Barrichello</span>, um excelente piloto, que dirige muito melhor do que a maior parte das pessoas, e existe o <span class="bold">Seu Pereira</span>, acostumado a dirigir o seu Fusca do sítio até a cidade, desde que decidiu aposentar o Tostado, seu fiel pangaré, e substituí-lo por um automóvel.</p>
								<p>A criatividade é uma capacidade e, como tal, precisa ser desenvolvida e treinada. Quanto mais isso for feito, mais criativa a pessoa será, não porque tenha recebido uma dose extra de criatividade quando nasceu, mas porque tratou de desenvolvê-la. A boa notícia é que o potencial criativo pode ser recuperado. Ele está lá, escondido em algum canto do nosso ser. E existem meios de encontrá-lo e de restaurá-lo, para que você volte a ser criativo como quando tinha dois anos de idade.</p>
								<h3>Mito 2: A criatividade surge de repente, naqueles grandes momentos de iluminação, reconhecidos como “Eureka”</h3>
								<p>É incrível quando podemos presenciar — ou experimentar — um grande momento <span class="bold">“Eureka”</span>. É uma experiência e tanto. E é verdade. A grande ideia surge quando menos esperamos, no meio da madrugada, enquanto fazemos a barba ou no meio da caminhada matinal. Mas esse momento é apenas o apogeu de uma longa e cansativa jornada, regada a muito suor e lágrimas, com fases de iluminação e frustração, de fadiga e de revelação.</p>
								<p>A criatividade nunca surge de repente. Ela sempre é fruto de muito trabalho e de muito preparo. Mas o grande momento, aquele em que a grande ideia surge e finalmente encontramos a solução que tanto buscamos, acaba recebendo muito mais atenção. E é bom que seja assim. São os momentos que fazem tudo valer a pena.</p>
								<h3>Mito 3: A criatividade só é importante nas “carreiras criativas”</h3>
								<p>É verdade que algumas profissões exigem que se use muito mais a criatividade do que em outras. Mas não é verdade que a criatividade não tenha lugar em algumas linhas de trabalho.</p>
								<p>Se pensamos em profissionais da criatividade, logo nos vêm à mente os publicitários. No ambiente das agências, as pessoas referem-se aos profissionais do departamento de criação como “os criativos”. A criatividade também é comumente relacionada aos profissionais das artes, por causa da grande confusão entre a criatividade e a capacidade de criar uma obra de arte. É muito importante reconhecermos a possibilidade da existência de um profissional com uma grande capacidade técnica, que estudou e se preparou durante muito tempo, e que é capaz de compor uma belíssima sinfonia ou de criar uma escultura incrível, sem que essas obras sejam, necessariamente, uma grande expressão de criatividade. Da mesma forma, um engenheiro ou um arquiteto, que possui o conhecimento técnico inerente à sua profissão, pode criar um novo projeto ou produto que encanta a todos, que vai muito além do que seria necessário, por meio da aplicação da criatividade no processo.</p>
								<h3>Mito 4: A criatividade não pode ser ensinada</h3>
								<p>Eu escrevi um <a href="https://www.marcosmayer.com.br/artigo/criatividade-pode-ser-ensinada" target="_blank">artigo inteiro</a>, apenas para rebater esse mito, porque ele é muito nocivo. Se alguém acredita que não pode aprender a ser criativo, que não pode desenvolver sua criatividade, não fará nenhum esforço nessa direção. Segundo esse mito, que é criativo, já nasceu assim. E apenas algumas poucas pessoas nascem criativas.</p>
								<p>A criatividade pode ser ensinada e, ainda mais importante, a criatividade pode ser desenvolvida. Vejam o que <span class="bold">Sir Ken Robinson</span> escreveu em um artigo em que ela trata da criatividade:</p>
								<p class="citacao">“A criatividade é formada a partir de uma série de poderes que todos temos, em virtude de sermos humanos. A criatividade é possível em todas as áreas da vida humana, na ciência, nas artes, na matemática, na tecnologia, na cozinha, no ensino, na política, nos negócios, no que você pensar. E como muitas capacidades humanas, nossos poderes criativos podem ser cultivados e refinados. Fazer isso envolve um crescente domínio de habilidade, conhecimento e ideias.”</p>
								<p>O único pré-requisito para que você possa considerar-se uma pessoa com um enorme potencial criativo é o seguinte: você precisa ser humano. Simples, não é? Mas, se é tão simples assim, como podemos desbloquear e desenvolver esse potencial?</p>
								<h2>Como profissionais podem desenvolver sua criatividade</h2>
								<p>Se você chegou até aqui, já deve estar convencido da importância da criatividade. Empresas precisam de um ambiente criativo e inovador, e, para isso, precisam de equipes de profissionais altamente criativos. Nesse ponto, a próxima pergunta, obviamente, seria: como as empresas e os profissionais podem conseguir isso?</p>
								<p>Vamos começar pelos profissionais. Eu escrevi um <a href="https://www.marcosmayer.com.br/artigo/criatividade-30-dicas-de-como-ser-mais-criativo" target="_blank">artigo com 30 dicas de como ser mais criativo</a>. São dicas simples, de fácil execução, e que funcionam, para qualquer pessoa, de qualquer idade e em qualquer ambiente. Entretanto, o nosso foco aqui é na criatividade no ambiente de trabalho. O estudo realizado pela Adobe mostrou como os profissionais se sentem pressionados a ser cada vez mais produtivos. O tempo é curto e as tarefas são gigantes e muitas. Como encontrar tempo para desenvolver a criatividade nesse contexto? Felizmente, algumas dicas simples podem ser postas em prática  até pelo mais ocupado dos executivos. Vamos a elas.</p>
								<h3>Dica 1: Mude a sua rotina</h3>
								<p>Pesquisas mostram que estar—ou passar algum tempo—em um ambiente com o qual não estamos familiarizados pode aguçar nossa criatividade.</p>
								<p>Um estudo realizado por pelos psicólogos e professores <span class="bold">David Strayer</span>, da <span class="bold">Universidade de Utah</span>, e <span class="bold">Ruth Ann Atchley</span> e <span class="bold">Paul Atchley</span>, da <span class="bold">Universidade de Kansas</span>, ambas nos Estados Unidos, demonstrou algumas informações muito relevantes. De acordo com o estudo, depois de quatro dias de imersão na natureza, em que os participantes não puderam levar seus dispositivos de comunicação e multimídia, eles tiveram um aumento de 50% na sua capacidade criativa e de solução de problemas.</p>
								<p>Evidentemente, neste exato momento você deve estar pensando: “Não existe nenhuma possibilidade de eu passar quatro dias desconectado, muito menos em algum retiro na natureza”. E eu entendo essa reação. Ela é muito natural. Mas não descarte essa possibilidade tão rápido, porque quatro dias assim podem tornar os outros trezentos e sessenta e um dias do ano muito melhores, em diversos aspectos. Mas, mesmo que você não consiga passar quatro dias na selva, existe uma série de ações menores, que podem ser encaixadas no cotidiano, e que produzem efeitos semelhantes, ainda que em escala e intensidade inferiores.</p>
								<p>Levante-se, pela manhã, e não toque em seu celular durante a primeira hora do dia. Tome um café da manhã diferente do que você está acostumado. Vista uma roupa que você não costuma usar, aproveitando o movimento das empresas que estão mudando seu dress code. Faça um caminho diferente para o trabalho e observe atentamente o que está acontecendo á sua volta. Faça uma reunião em pé ou sentado no chão, em vez de usar uma típica sala de reuniões. Saia para o almoço e procure uma comida que você nunca comeu antes. Vá a um restaurante tailandês e saboreie sua cozinha. Na volta, passe na banca de jornais e compre uma revista que você jamais pensaria em comprar. E leia essa revista. Deu pra entender a ideia, não deu? O mundo está cheio de coisas interessantes acontecendo à nossa volta. Se nós apenas tirarmos nossos olhos da tela do celular, do tablet ou do computador, perceberemos isso. </p>
								<h3>Dica 2: Peça feedback de fontes diferentes</h3>
								<p>Você tem ideias. Todos as temos. Nesse momento, o melhor que você pode fazer é ir conversar com pessoas que não tem nada que ver com a ideia que você teve, mesmo que—e principalmente—essas pessoas encontrem problemas nela.</p>
								<p><span class="bold">Rufus Griscom</span>, fundador e CEO da <span class="bold">Heleo</span>, disse o seguinte: <span class="destaque">“Ideias são como pessoas. Elas não gostam de viver isoladas ou tratadas com ciúme. Elas gostam de se misturar e de interagir com outras ideias”</span>. Ao afirmar isso, ele falou de um dos principais fatores de sucesso de um processo criativo. E também deixa claro que nós, os criadores de ideias, devemos deixá-las livres, porque é assim que elas funcionam melhor.</p>
								<p>Então jogue a sua ideia no ar. Converse sobre ela com a copeira da sua empresa, quando for tomar um cafezinho. Converse com seu colega de um departamento sem nenhuma relação direta com a ideia. Pergunte a opinião da sua mãe. Ligue para ela e diga: “Mãe, tive uma ideia aqui no trabalho. O que acha dela?”. E compartilhe essa ideia com o motorista do Uber no caminho para casa. Ouvir reações e comentários a respeito da sua ideia pode ser um processo muito rico, e pode te surpreender.</p>
								<h3>Dica 3: Precisa resolver um problema? Pare de pensar nele.</h3>
								<p>Você tem um problema que precisa ser resolvido. Então você faz uma imersão no tema e tenta de tudo, usando a sua mente consciente, para chegar a uma solução. Mas você precisa saber de uma coisa: a sua mente consciente não é muito criativa. Desculpe. Já sua mente inconsciente... Ela é genial! Mas você precisa deixá-la trabalhar. A criatividade precisa de espaço para funcionar e, para que isso seja possível, você precisa parar de pensar no seu problema.</p>
								<p>Para tratar dessa questão, de deixar a mente trabalhar e fazer o que só ela é capaz de fazer, muitos executivos praticam a meditação. Meditar pode trazer resultados incríveis para a criatividade, além do bem-estar em geral. Mas pode ser que você não goste da ideia de meditar, o que seria uma pena. Também pode ser que você argumente que não tem o tempo disponível para meditar. Felizmente, existem outras maneiras de capturar o benefício de uma mente divagante.</p>
								<p>Muitas pessoas fazem caminhadas. Seja pela manhã ou à noite, ou mesmo durante o dia, dependendo do seu ambiente de trabalho, uma caminhada, assim como a meditação, pode transformar a situação. Mas o mesmo pode acontecer com a prática de algumas atividades mais mundanas, como lavar o carro, pintar uma cerca, cuidas das plantas ou lavar a louça. Qualquer coisa que permita que seu cérebro funcione no modo inconsciente. </p>
								<h3>Dica 4: Abrace os limites</h3>
								<p><span class="bold">Marissa Mayer</span>, CEO do <span class="bold">Yahoo</span>, fez a seguinte afirmação quando era <span class="bold">Vice-Presidente de Produtos de Busca e Experiência do Usuário</span> no <span class="bold">Google</span>: <span class="destaque">“A criatividade ama restrições”</span>.</p>
								<p>Entenda: criatividade sem limites não é criatividade, é imaginação. A imaginação é uma parte importante no processo criativo, mas ela, por si só, não tem nenhum compromisso com a resolução de um problema. É aí que entra em ação a criatividade, que, para funcionar, precisa conhecer e considerar limites. Essa é a raiz da grande dificuldade que eu tenho com a ideia de brainstorms. Um brainstorm é um processo em que utilizamos nossa imaginação, mas não é um processo de criatividade.</p>
								<p>Para que alguém seja criativo em determinada área, essa pessoa precisa conhecê-la. Eu não seria capaz, hoje, de ter ideias criativas a respeito da fabricação de órgãos humanos artificiais, porque eu não sei nada a esse respeito. Eu não conheço seus limites, nem técnicos, nem econômicos, nem de qualquer ordem. Para que sejam criativas, se acordo com a definição de criatividade que adotamos, as ideias precisam ter valor. Para que esse seja o caso, todos os limites precisam ter sido considerados. E, como um exercício, saber quais são os limites e tentar encontrar meio de rompê-los é uma ótima forma de ser criativo.</p>
								<h2>Como as empresas podem promover a criatividade</h2>
								<p>A primeira e mais importante maneira de uma empresa promover a criatividade e um ambiente criativo é permitir—e até incentivar—o erro. Veja o que disse <span class="bold">Antonio Lucio</span>, atual CMO Global do <span class="bold">Facebook</span>, quando era CMO da <span class="bold">HP</span>: <span class="destaque">“Erros fazem parte da trajetória. Nós os cometemos todos os dias. Se não os cometermos diariamente, é porque não estamos empurrando os limites e desafiando o sistema suficientemente”</span>. É claro que entre uma empresa dar esse tipo de declarações e o ambiente da empresa refletir, de fato, essa máxima, pode haver uma grande distância.</p>
								<p>Uma outra forma de promover a criatividade é abraçar o que é diferente. Podem ser pessoas diferentes, que pensam diferente, que se vestem diferente e que tem opiniões diferentes. Também pode ser um ambiente diferente, com jeitos diferentes de fazer reuniões e ambientes montados de forma diferente. Um ambiente assim, com tanta diversidade, é uma ótima maneira de gerar ideias diferentes e diferentes formas de pensar.</p>
								<p>O terceiro meio para promover a criatividade é criando algumas ações “formais” para o desenvolvimento da criatividade. Pode parecer contraditório formalizar a criatividade, mas, muitas vezes, é o melhor jeito de começar a criar uma cultura de criatividade e inovação. Existem diversas formas diferentes de fazer isso:</p>
								<ul class="topics">
									<li>Uma maneira, que muitas empresas já utilizam, é criar uma competição anual de inovação. Em competições assim, os funcionários de uma empresa, independentemente de sua área de atuação, são convidados a criar ideias inovadoras e sugestões de como de pode melhorar o negócio da empresa. As melhores propostas são premiadas e colocadas em prática.</li>
									<li>Outra maneira é disponibilizar aos funcionários uma parte de seu tempo para que eles possam dedicar-se à pesquisa e ao desenvolvimento de boas ideias inovadoras que podem vir a ajudar a empresa. Normalmente, o tempo disponível fica em torno de 15% a 20%.</li>
									<li>Algumas empresas, originariamente da área de tecnologia, criaram eventos que ficaram conhecidos como hack , em que eles juntam funcionários de diversas áreas, durante um dia ou alguns dias, para que eles se juntem para colaborar, incubar e elaborar ideias, para inovar produtos e processos.</li>
								</ul>
								<p>Evidentemente, podem haver muitas outras formas de incentivar e promover a criatividade dentro das empresas. E isso é fácil de explicar. Empresas que são, reconhecidamente, criativas tem essa característica registrada em seu “DNA”, o que, nas organizações, chamamos de cultura. E ninguém transforma a cultura, de qualquer organização que seja, apenas decidindo que vai mudar. Não funciona assim. Então é preciso colocar em prática uma excelente expressão, muito conhecida em inglês, que diz: “fake it until you make it”. Literalmente, a tradução seria: “finja até que você o faça”. A ideia é fazer uso de artifícios que façam parecer que algo acontece naturalmente, até que, de fato, as coisas aconteçam com naturalidade, tornando obsoletos os artifícios.</p>
								<p>Criar um ambiente criativo em uma empresa é uma mudança cultural. Demanda tempo e esforço. E, como tudo que é importante: só existe um jeito de obter sucesso: começando. Fake it until you make it.</p>
								<h2>Os principais benefícios da criatividade</h2>
								<p>Conforme estudava o tema da criatividade, eu ficava cada vez mais convencido de sua importância. Comecei a escrever e a falar sobre o tema, nas redes sociais e em palestras que dava pelo Brasil. Nessa caminhada, comecei a perceber que a urgência na ampla divulgação da importância da criatividade não era compartilhada pela maior parte das pessoas e empresas. A criatividade fica no campo das coisas que são bacanas, divertidas e interessantes, mas não essenciais. Por mais que diversas pesquisas mostrem a importância crescente da criatividade, ela continua não tendo o devido reconhecimento.</p>
								<p>Então, direcionei o foco da minha pesquisa para tentar descobrir quais são os motivos que fazem com que isso seja assim. Além dos mitos que cercam o tema e que atrapalham muito na sua compreensão, descobri que falta uma abordagem mais prática e clara de quais são os principais benefícios de um estilo de vida criativo. Ou seja, faltava as pessoas e as empresas saberem o que fazer com ela. Trabalhei, então, para tentar responder a esta questão: quais são os principais benefícios da criatividade?</p>
								<p>A resposta que eu encontrei foi o <span class="destaque"><a href="https://www.sejaoseucase.com.br" target="_blank">C.A.S.E.</a></span>, um acrônimo que representa as quatro principais capacidades que são desenvolvidas quando passamos a levar um estilo de vida criativo. São elas: <span class="bold">confiar</span> (em si mesmo), <span class="bold">adaptar</span> (adaptar-se às mudanças), <span class="bold">solucionar</span> (problemas) e <span class="bold">expressar</span> (sua verdadeira identidade). Essas quatro capacidades permitem a um ser humano viver plenamente, sendo capaz de construir uma vida com sentido e senso de realização. E acontece que essas exatas quatro características se aplicam, da mesma forma, a organizações.</p>
								<p>1. <span class="bold">Confiar em si mesmo</span>, ou ter autoconfiança, é o começo de tudo. Acreditar que você é capaz de realizar algo não é nenhuma garantia de que você vai conseguir, mas não acreditar garante que você não consiga. A autoconfiança é o tipo de qualidade que é facilmente percebida. Quando alguém que confia em si mesmo entra em um ambiente, nós logo notamos a diferença, no jeito de andar, na postura e na atitude. A autoconfiança é uma característica atraente.</p>
								<p>Vejam o que disse <span class="bold">E. E. Cummings</span> (1894 – 1962), um autor e poeta americano, a esse respeito: <span class="destaque">“Uma vez que acreditamos em nós mesmos, nós podemos arriscar a curiosidade, o espanto, o prazer espontâneo ou qualquer experiência que revela o espírito humano”</span>.</p>
								<p>Quem confia em si mesmo não sente nenhuma necessidade de provar seu valor aos outros. Ele conhece o seu valor. Existe uma grande diferença entre “se achar” e se conhecer e confiar em si. Quem se acha, precisa tentar provar, o tempo todo, que é, porque, na verdade, ele apenas acha que é. Quem confia em si, sabe do que é capaz e, não menos importante, conhece seus limites, e está em paz com eles, o que não o impede de assumir riscos e empurrar esses limites.</p>
								<p>Talvez a questão mais importante quando falamos em autoconfiança seja: se você não acredita em você mesmo, como espera que outros acreditem?</p>
								<p>A boa notícia é que, como toda capacidade humana, a autoconfiança pode ser desenvolvida. Mas como podemos desenvolver nossa autoconfiança? Da mesma forma como conquistamos a confiança de qualquer pessoa: precisamos cumprir as promessas que fazemos a nós mesmos, de forma consistente, através do tempo. Existe uma série de ações e técnicas que podemos nos ajudar, mas no final das contas, temos que conquistar a nossa própria confiança.</p>
								<p><span class="destaque">Como se aplica às empresas</span>: quando pensarmos nos principais benefícios da criatividade, devemos lembrar que as empresas são um organismo vivo, que as empresas são as pessoas que as formam. Assim, uma empresa que confia em si mesma é uma empresa em que os funcionários sabem do que ela é capaz e confiam em seu potencial de lhes oferecer um ambiente de trabalho que, em última instância, promoverá o seu crescimento pessoal. É uma empresa que cumpre suas promessas, feitas tanto para o mercado consumidor—se público externo—, quanto aos seus funcionários—seu público interno. Além disso, é fácil reconhecer uma empresa que tem autoconfiança. E essa confiança é transmitida para todos.</p>
								<p>2. <span class="bold">Adaptar-se rapidamente às constantes mudanças</span> é uma outra capacidade fundamental. Cansamos de ouvir que a única constante é a mudança. Vemos o mundo mudando rapidamente à nossa volta e a primeira reação da maior parte das pessoas é negativa. Mudar torna-se algo dramático, cercado de traumas que nos paralisam. A todo momento, alguém profetiza, mais uma vez, o fim do emprego, um verdadeiro apocalipse para a raça humana, que será substituída por seres com inteligência artificial, tornando-nos obsoletos no nosso trabalho. Tudo isso, provavelmente, vai mesmo acontecer. E pode ser algo muito bom.</p>
								<p>Pessoas criativas não apenas não temem a mudança, mas, genuinamente, gostam dela. Isso se deve, principalmente, ao fato de que toda mudança traz consigo uma oportunidade. Claro, nem toda mudança é positiva. Esse tipo de pensamento, além de ser irreal, não ajudaria em nada. Mas toda mudança traz a possibilidade de aprendizado, crescimento e aprimoramento.</p>
								<p>O segredo, nesse caso, é uma mudança de atitude e de mentalidade. A partir da certeza—uma das poucas que se pode ter—de que mudanças sempre vão acontecer, você pode entrar em pânico toda vez que uma surge no horizonte, ou pode se preparar para ela, aguardando ansiosamente por tudo de bom que ela pode trazer. Particularmente, prefiro a segunda opção.</p>
								<p><span class="destaque">Como se aplica às empresas</span>: não é preciso dizer muito a respeito de como a capacidade de adaptação às mudanças se aplica às empresas, já que é exatamente essa capacidade a característica mais desejada de profissionais e empresas criativas, conforme a pesquisa que foi apresentada no início desse artigo. No ambiente das empresas, o principal benefício da atitude de abraçar e lidar de forma apropriada com as mudanças é chamado de inovação.</p>
								<p>3. <span class="bold">A capacidade de solucionar problemas</span> é uma das mais importantes para qualquer pessoa. A vida pode ser encarada como uma sucessão de problemas a serem resolvidos, desde escolher uma roupa que consideramos adequada para a nossa atividade do dia, até decidir pela aquisição de uma nova empresa, nós enfrentamos um número enorme de problemas todos os dias. A maior parte deles nós não encaramos como um problema a ser resolvido, porque tomamos decisões quase mecanicamente.</p>
								<p>Importante ressaltar que não se trata de ter o conhecimento técnico ou a habilidade necessária para resolver qualquer problema com as suas próprias mãos. Se o seu carro tem um problema mecânico, é melhor entregá-lo a um profissional capacitado a resolvê-lo, da mesma forma que se você tem um problema de saúde, é melhor ir a um médico.</p>
								<p>Estamos falando de deparar-se com um problema, e enxergar um desafio a ser vencido. De estudar um problema e não permitir que ele o paralise. A coisa mais importante na hora de solucionar um problema, do ponto de vista da criatividade, é a capacidade de compreender qual é o problema, fazendo as perguntas certas. Veja um exemplo simples.</p>
								<p>Um problema pode ser: “Como vamos dar a melhor festa de aniversário possível para o nosso filho, que vai completar oito anos de idade?”. Mas, se pensarmos nesse problema, de forma criativa, fazendo as perguntas certas, podemos chegar à conclusão de que o problema, na verdade, é outro: “Como podemos tornar o aniversário de oito anos do nosso filho uma experiência maravilhosa para ele?”. Isso pode mudar tudo, porque pode ser que a resposta não seja uma festa de aniversário, mas, sim, acampar em família no final de semana.</p>
								<p>Veja as seguintes citações a respeito da solução de problemas, que nos ajudam a entender o tema. Elas são atribuídas a Albert Einstein:</p>
								<p class="citacao">“Não é que eu seja tão inteligente, eu apenas penso nos problemas por mais tempo.”</p>
								<p class="citacao">“Nós não podemos resolver nossos problemas com o mesmo tipo de pensamento que usamos para criá-los.”</p>
								<p class="citacao">“Se eu tivesse uma hora para resolver um problema e a minha vida dependesse de sua solução, eu passaria os primeiros cinquenta e cinco minutos determinando a pergunta certa a ser feita, porque uma vez que eu soubesse qual é a pergunta certa, eu poderia resolver o problema em menos de cinco minutos.”</p>
								<p>Esse é o tipo de pensamento que precisamos desenvolver para nos tornarmos bons solucionadores de problemas.</p>
								<p><span class="destaque">Como se aplica às empresas</span>: o <span class="bold">Fórum Econômico Mundial</span> publicou um relatório muito interessante, com o título de <span class="destaque">“The Future of Jobs”</span> (“O Futuro dos Empregos”), que apresenta os resultados de uma pesquisa realizada com CHROs e outros executivos sênior das áreas de talentos e estratégia, de 371 das principais empresas empregadoras globais, que representam mais de 13 milhões de funcionários. Basicamente, a pesquisa tinha o objetivo de descobrir o que as atuais mudanças econômicas e tecnológicas significam, especificamente para a empregabilidade, as habilidades e o recrutamento. Quero destacar aqui, do ranking das <span class="destaque">10 Habilidades Mais Importantes em 2020</span> que as empresas procuram em seus funcionários e candidatos, a primeira colocada: <span class="destaque">solução de problema complexos</span>. Esse ranking também havia sido realizado em 2015. De 2015 a 2020 houve diversas mudanças no ranking, como era de se esperar, mas a primeira colocada havia sido a mesma.</p>
								<p>4. <span class="bold">Expressar a si mesmo</span>, com integridade e genuinidade, soa muito mais fácil do que é, de fato. Por uma série de razões históricas e culturais, a maior parte das pessoas cria um personagem e tenta vivê-lo, tentando convencer os outros de que aquela imagem é, de fato, a expressão do que elas são. Todas as pessoas que querem fazer parte de algum grupo, tribo ou comunidade, sabe que, ainda que implícitas, existem uma série de regras de comportamento, quando ao que vestir, o que dizer, que música curtir, como andar e até sobre o que pensar. E como todo mundo quer fazer parte de algo, as pessoas abrem mão de sua individualidade para conseguir isso.</p>
								<p>O maior problema com isso é que quando você é igual a outras milhares, ou até milhões, de pessoas, a concorrência é muito grande. Por que alguém deveria escolher você, se iguais a você existem tantos outros? E isso se aplica à vida pessoa e profissional. Por que um empregador escolheria você, se existem tantos outros iguais a você? E aí passa a ser apenas uma questão de sorte.</p>
								<p>Ser a sua versão original e autêntica é a melhor decisão que alguém tem que tomar. E o motivo é simples. Só existe uma pessoa no mundo inteiro que é assim: você. Pessoas assim nos atraem, por serem interessantes. A gente vê alguém assim e logo pensa: “Essa pessoa tem algo diferente, não sei bem o que é”. Claro que não sabemos, porque é a primeira vez que vemos alguém assim. Não existe outra.</p>
								<p>Mas ser autêntico e original não é suficiente. É preciso ser capaz de expressar quem você é. É necessário ter a capacidade de expressar as suas ideias, independentemente de qual meio você usa para fazê-lo. Pode ser a arte, pode ser a escrita, pode ser a fala, podem ser inúmeras formas, mas as ideias precisam sair de dentro da sua cabeça e ser expressadas para que o mundo inteiro possa conhecê-las. Nós nunca tivemos tanta necessidade de ideias diferentes, porque as velhas ideias não têm resolvido os nossos maiores problemas.</p>
								<p><span class="destaque">Como se aplica às empresas</span>: se você é familiarizado com o conceito apresentado no livro <span class="destaque">“Posicionamento. A Batalha por Sua Mente”</span>, escrito por <span class="bold">Al Ries</span> e <span class="bold">Jack Trout</span>, em 1980, você já sabe o que vou dizer em seguida. Veja um dos conceitos centrais do livro: <span class="destaque">“O jeito mais fácil de entrar na mente de uma pessoa é sendo o primeiro”</span>. Não vou entrar em detalhes aqui, mas a ideia é que uma empresa precisa ser original e autêntica, e precisa expressar isso de maneira clara e singular, se quiser vencer a batalha por um espaço na mente do consumidor. Ainda mais nos dias de hoje, em que a atenção é o maior objeto de desejo de qualquer marca. Ah, se você não conhece o livro citado acima, eu recomendo fortemente que você o leia. É incrível!</p>
								<h2>Conclusão</h2>
								<p>Você ficou curioso a respeito de quais são as outras habilidades dentre as 10 Habilidades Mais Importantes em 2020, apresentadas no relatório do Fórum Econômico Mundial? Veja os dois rankings abaixo, de 2015 e de 2020:</p>
								<h3>2015</h3>
								<ol>
									<li><span class="bold">Solução de problemas complexos</span></li>
									<li>Coordenar com outros</li>
									<li>Gestão de pessoas</li>
									<li><span class="bold">Pensamento crítico</span></li>
									<li>Negociação</li>
									<li>Controle de qualidade</li>
									<li>Orientação de serviço</li>
									<li>Julgamento de tomada de decisões</li>
									<li>Escutar ativamente</li>
									<li><span class="destaque">Criatividade</span></li>
								</ol>
								<h3>2020</h3>
								<ol>
									<li><span class="bold">Solução de problemas complexos</span></li>
									<li><span class="bold">Pensamento crítico</span></li>
									<li><span class="destaque">Criatividade</span></li>
									<li>Gestão de pessoas</li>
									<li>Coordenar com outros</li>
									<li>Inteligência emocional</li>
									<li>Julgamento de tomada de decisões</li>
									<li>Orientação de serviço</li>
									<li>Negociação</li>
									<li>Flexibilidade cognitiva</li>
								</ol>
								<p>Veja que a criatividade pulou da décima para a terceira posição, em um prazo de cinco anos. Mas o mais interessante é que as habilidades posicionadas como a primeira e a segunda mais importantes, em 2020, que são a solução de problemas complexos e o pensamento crítico, respectivamente, estão intrincadamente ligadas à criatividade e são até mesmo abrangidas por ela, em sua definição mais ampla.</p>
								<p>Não resta nenhuma dúvida de que <span class="destaque">a criatividade é a principal capacidade que os profissionais e as empresas devem procurar desenvolver</span>. A boa notícia é que é possível fazê-lo, assim como no caso de todas as outras habilidades listadas no ranking acima. Então, comece. Resgate todo o potencial criativo que, por uma série de razões, foi suprimido dentro de você.</p>
								<p>E prepare-se para futuro. Qualquer que seja ele.</p>
							</div>
							<a class="blog-post-voltar" href="/blog/">Voltar</a>
						</article>
					</div>
				</div>
			</div>
		</div>
		<div class="footer">
			<span class="footer-1">&copy; <?php echo date("Y"); ?> Marcos Mayer</span><span class="footer-2">&nbsp;-&nbsp;</span><span class="footer-3">Todos os direitos reservados</span>
		</div>
		<script src="../js/modernizr.custom.js"></script>
		<script src="../js/nav.js"></script>
		<script src="https://code.jquery.com/jquery-1.11.3.min.js" type="text/javascript"></script>
	</body>
</html>
